wandb_version: 1

batch_size:
  value: 40
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.09907292076927872
epochs:
  value: 10
hidden_layer_width:
  value: 16
lr:
  value: 7.56080316341194e-05
optim_type:
  value: Adam
project_name:
  value: mnist_torchkeras
