wandb_version: 1

batch_size:
  value: 176
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.596021205595185
epochs:
  value: 10
hidden_layer_width:
  value: 32
lr:
  value: 8.286670627386711e-05
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
