wandb_version: 1

batch_size:
  value: 64
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.03389346908708452
epochs:
  value: 10
hidden_layer_width:
  value: 48
lr:
  value: 5.319396602518499e-05
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
