wandb_version: 1

batch_size:
  value: 48
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.24858306835373367
epochs:
  value: 10
hidden_layer_width:
  value: 96
lr:
  value: 2.55418526992468e-05
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
