wandb_version: 1

batch_size:
  value: 40
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.03259508738393539
epochs:
  value: 10
hidden_layer_width:
  value: 128
lr:
  value: 0.028988993760271635
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
