wandb_version: 1

batch_size:
  value: 88
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.5880989884945115
epochs:
  value: 10
hidden_layer_width:
  value: 16
lr:
  value: 0.004295698265753442
optim_type:
  value: Adam
project_name:
  value: mnist_torchkeras
