wandb_version: 1

batch_size:
  value: 192
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.260627505535725
epochs:
  value: 10
hidden_layer_width:
  value: 64
lr:
  value: 0.003073372067877516
optim_type:
  value: Adam
project_name:
  value: mnist_torchkeras
