wandb_version: 1

batch_size:
  value: 48
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.575487977969066
epochs:
  value: 10
hidden_layer_width:
  value: 16
lr:
  value: 0.00015962361871142214
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
