wandb_version: 1

batch_size:
  value: 80
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.33099630139842656
epochs:
  value: 10
hidden_layer_width:
  value: 128
lr:
  value: 0.002083572160128837
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
