wandb_version: 1

batch_size:
  value: 136
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.12424157783386712
epochs:
  value: 10
hidden_layer_width:
  value: 32
lr:
  value: 1.233140152698663e-06
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
