wandb_version: 1

batch_size:
  value: 64
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.4648299789308405
epochs:
  value: 10
hidden_layer_width:
  value: 48
lr:
  value: 0.00900968753217986
optim_type:
  value: AdamW
project_name:
  value: mnist_torchkeras
