wandb_version: 1

batch_size:
  value: 96
ckpt_path:
  value: checkpoint.pt
dropout_p:
  value: 0.47526823460562295
epochs:
  value: 10
hidden_layer_width:
  value: 32
lr:
  value: 5.515708813317925e-06
optim_type:
  value: SGD
project_name:
  value: mnist_torchkeras
