wandb_version: 1

project_name:
  desc: null
  value: mnist_torchkeras
batch_size:
  desc: null
  value: 512
hidden_layer_width:
  desc: null
  value: 64
dropout_p:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0001
optim_type:
  desc: null
  value: Adam
epochs:
  desc: null
  value: 10
ckpt_path:
  desc: null
  value: checkpoint
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715251671
    t:
      1:
      - 1
      - 41
      - 55
      - 71
      2:
      - 1
      - 41
      - 55
      - 71
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      - 62
      - 65
      4: 3.9.19
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      4: epoch
      6:
      - 1
      - 2
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
      - 3
    - 1: train_acc
      5: 1
      6:
      - 1
      - 3
    - 1: lr
      5: 1
      6:
      - 1
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
      - 3
    - 1: val_acc
      5: 1
      6:
      - 1
      - 3
    - 1: best_val_acc
      5: 1
      6:
      - 1
      - 3
    session_history: code/_session_history.ipynb
