wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715242797
    t:
      1:
      - 1
      - 41
      - 55
      - 71
      2:
      - 1
      - 41
      - 55
      - 71
      3:
      - 2
      - 5
      - 14
      - 23
      - 62
      4: 3.9.19
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
lr:
  desc: null
  value: 0.001
dropout_p:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
